<a href="https://colab.research.google.com/github/apoorvapalled/Hands_on/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
a=[1,2,3,4,5,6,7,8,9]

In [6]:
type(a)

list

In [7]:
b=np.array(a)

In [8]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
type(b)

numpy.ndarray

In [10]:
np.array(range(0,15))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.linspace(0,10,8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [12]:
c=[[1,2,3],[10,20,30]]

In [13]:
np.array(c)

array([[ 1,  2,  3],
       [10, 20, 30]])

In [14]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
first_thirty=np.linspace(0,29,30)
print(first_thirty)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]


In [17]:
first_thirty.shape

(30,)

In [18]:
first_thirty.reshape(3,10)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]])

In [19]:
first_ten= np.arange(0,10)
print(first_ten)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
first_ten+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
first_ten*first_ten

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [22]:
first_ten[0]=100
first_ten

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [23]:
first_ten[:] = 99

In [24]:
first_ten

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])